### PR TITLE
Async wrapper

### LINKED ISSUE #3: NeoVim support
Would you be interested in making this work for [NeoVim](https://neovim.io/) as well? The tagline "A **minimal** package manager for **Vim 8**" suggests not, but I wonder how determined you are to keep things minimal?

### PR DESCRIPTION
**Pull request by k-takata**
This takes over #4 and closes #3.

* Update document. (Mentions async.vim and NeoVim.)
* Use git-subtree to track async.vim.
  - Add a script for pulling latest async.vim.

### CODE REVIEW

**Comment by k-takata** [comment]
@nelstrom 
I only tested this on Vim 8, so can you try this also on NeoVim?

**Comment by nelstrom** [comment]
I will do. (I've been travelling these last couple of days and haven't had a chance yet.)

**Comment by k-takata** [comment]
Okay, I will wait.

**Comment by nelstrom** [comment]
Good job! This works for me in NeoVim (on a mac).

**Comment by k-takata** [comment]
thx!

**Pull request merged**
