### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by k-takata**
Related: #13

### CODE REVIEW

**Comment by k-takata** [comment]
I tried to use [vim-appimage](https://github.com/vim/vim-appimage/releases) for using the latest version of Vim, but it failed with the following error:
```
fuse: failed to open /dev/fuse: Operation not permitted
```
https://travis-ci.org/k-takata/minpac/builds/223617602#L184

Does anyone know about this?

**Comment by k-takata** [comment]
AppImages require FUSE. https://github.com/probonopd/AppImageKit/wiki/FUSE
And current version of travis-ci doesn't support FUSE.
FUSE can be used on Ubuntu Trusty beta, but it requires sudo: https://github.com/travis-ci/travis-ci/issues/1100#issuecomment-160169121

There is a [fallback](https://github.com/probonopd/AppImageKit/wiki/FUSE#fallback) which doesn't require FUSE, but it also requires sudo.

**Comment by probonopd** [comment]
Type 2 AppImages (the currently recommended version) can directly be extracted. Run the AppImage with `--appimage-extract` to extract the contents of the AppImage. No root needed.

**Comment by k-takata** [comment]
Unfortunately, vim-appimage uses type 1 AppImage.

**Comment by k-takata** [comment]
@probonopd 
https://github.com/probonopd/AppImageKit/wiki/FUSE#fallback says:

> you might have an experimental type 2 AppImage.

If type 2 is the recommended version, I think this part should be updated.

**Comment by k-takata** [comment]
I decided not to use vim-appimage this time.

**Pull request merged**
